/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Estudiante
 */
public class DashBoard extends javax.swing.JFrame {

     int xMouse, yMouse;
    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        initComponents();
        
        Pantalla_Medico p1 = new Pantalla_Medico();
        ShowPanel(p1);
    }
    
    //[0,102,204]
    //[0,153,255]

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        MedicoPanel = new javax.swing.JPanel();
        btnMedico = new javax.swing.JLabel();
        PacientePanel = new javax.swing.JPanel();
        btnPaciente = new javax.swing.JLabel();
        CitaPanel = new javax.swing.JPanel();
        btnCita = new javax.swing.JLabel();
        line = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        bg.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 900, 540));

        MedicoPanel.setBackground(new java.awt.Color(0, 102, 204));

        btnMedico.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnMedico.setForeground(new java.awt.Color(255, 255, 255));
        btnMedico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMedico.setText("MÉDICO");
        btnMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMedicoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMedicoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMedicoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout MedicoPanelLayout = new javax.swing.GroupLayout(MedicoPanel);
        MedicoPanel.setLayout(MedicoPanelLayout);
        MedicoPanelLayout.setHorizontalGroup(
            MedicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        MedicoPanelLayout.setVerticalGroup(
            MedicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bg.add(MedicoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 60));

        PacientePanel.setBackground(new java.awt.Color(0, 102, 204));

        btnPaciente.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnPaciente.setForeground(new java.awt.Color(255, 255, 255));
        btnPaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPaciente.setText("PACIENTE");
        btnPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPacienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPacienteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPacienteMousePressed(evt);
            }
        });

        javax.swing.GroupLayout PacientePanelLayout = new javax.swing.GroupLayout(PacientePanel);
        PacientePanel.setLayout(PacientePanelLayout);
        PacientePanelLayout.setHorizontalGroup(
            PacientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
            .addGroup(PacientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PacientePanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PacientePanelLayout.setVerticalGroup(
            PacientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(PacientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PacientePanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        bg.add(PacientePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 150, 60));

        CitaPanel.setBackground(new java.awt.Color(0, 102, 204));

        btnCita.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnCita.setForeground(new java.awt.Color(255, 255, 255));
        btnCita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCita.setText("CITA");
        btnCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCitaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCitaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCitaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout CitaPanelLayout = new javax.swing.GroupLayout(CitaPanel);
        CitaPanel.setLayout(CitaPanelLayout);
        CitaPanelLayout.setHorizontalGroup(
            CitaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
            .addGroup(CitaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CitaPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnCita, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        CitaPanelLayout.setVerticalGroup(
            CitaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(CitaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CitaPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnCita, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        bg.add(CitaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        line.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout lineLayout = new javax.swing.GroupLayout(line);
        line.setLayout(lineLayout);
        lineLayout.setHorizontalGroup(
            lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        lineLayout.setVerticalGroup(
            lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        bg.add(line, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 450, 10));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(153, 153, 0));
        jButton1.setForeground(new java.awt.Color(102, 102, 0));
        jButton1.setText("-");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        header.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 20, 20));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 51));
        jButton2.setText("X");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        header.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(853, 10, 20, 20));

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMedicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMedicoMouseEntered
        MedicoPanel.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_btnMedicoMouseEntered

    private void btnMedicoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMedicoMouseExited
        MedicoPanel.setBackground(new Color(0,102,204));
    }//GEN-LAST:event_btnMedicoMouseExited

    private void btnMedicoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMedicoMousePressed
        Pantalla_Medico p1 = new Pantalla_Medico();
        ShowPanel(p1);
    }//GEN-LAST:event_btnMedicoMousePressed

    private void btnPacienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPacienteMouseEntered
        PacientePanel.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_btnPacienteMouseEntered

    private void btnPacienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPacienteMouseExited
        PacientePanel.setBackground(new Color(0,102,204));
    }//GEN-LAST:event_btnPacienteMouseExited

    private void btnPacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPacienteMousePressed
        Pantalla_Paciente p2 = new Pantalla_Paciente();
        ShowPanel(p2);
    }//GEN-LAST:event_btnPacienteMousePressed

    private void btnCitaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCitaMouseEntered
        CitaPanel.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_btnCitaMouseEntered

    private void btnCitaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCitaMouseExited
        CitaPanel.setBackground(new Color(0,102,204));
    }//GEN-LAST:event_btnCitaMouseExited

    private void btnCitaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCitaMousePressed
        Pantalla_Cita p3 = new Pantalla_Cita();
        ShowPanel(p3);
    }//GEN-LAST:event_btnCitaMousePressed

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
         int x = evt.getXOnScreen();
         int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }
    
    public void ShowPanel(JPanel p){
        
        p.setSize(900, 540);
        p.setLocation(0, 0);
        
        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CitaPanel;
    private javax.swing.JPanel MedicoPanel;
    private javax.swing.JPanel PacientePanel;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel btnCita;
    private javax.swing.JLabel btnMedico;
    private javax.swing.JLabel btnPaciente;
    private javax.swing.JPanel content;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel line;
    // End of variables declaration//GEN-END:variables
}
